-- Schema for BurgerDB
DROP DATABASE IF EXISTS BurgerDB;
CREATE DATABASE BurgerDB;

USE BurgerDB;

CREATE TABLE Burgers (
    BurgersID INT PRIMARY KEY AUTO_INCREMENT,
    BurgerName VARCHAR(30) NOT NULL,
    DEVOURED BOOLEAN NOT NULL DEFAULT FALSE
);